export const Users = [
  {
    id: 1,
    profilePicture: "person/1.png",
    username: "Adrian	Slater",
  },
  {
    id: 2,
    profilePicture: "person/2.png",
    username: "Dominic	Henderson",
  },
  {
    id: 3,
    profilePicture: "person/3.png",
    username: "Victor	Lambert",
  },

  {
    id: 5,
    profilePicture: "person/5.png",
    username: "Luke	Jackson",
  },
  {
    id: 6,
    profilePicture: "person/6.png",
    username: "Samantha	Martin",
  },
  {
    id: 7,
    profilePicture: "person/7.png",
    username: "Bella	Kerr",
  },
  {
    id: 8,
    profilePicture: "person/8.png",
    username: "Donna	Carr",
  },
  {
    id: 9,
    profilePicture: "person/9.png",
    username: "Maria	Parsons",
  },
  {
    id: 10,
    profilePicture: "person/10.png",
    username: "Sally	Wallace",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.avif",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
    share: 3,
  },
  {
    id: 2,
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
    share: 3,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
    share: 3,
  },
  {
    id: 4,
    photo: "assets/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
    share: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
    share: 3,
  },
  {
    id: 6,
    photo: "assets/post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
    share: 3,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
    share: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
    share: 3,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
    share: 3,
  },
  {
    id: 10,
    photo: "assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
    share: 3,
  },
];
